# Generated by Django 6.0.4 on 2026-04-12 16:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('resource', models.CharField(default='', max_length=64)),
                ('details', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'audit_logs',
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=16)),
                ('timestamp', models.DateTimeField(db_index=True, default=datetime.datetime.utcnow)),
                ('decision', models.CharField(max_length=16)),
                ('confidence', models.FloatField()),
                ('reason', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('signals_json', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'decisions',
            },
        ),
        migrations.CreateModel(
            name='FailedLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'failed_login_attempts',
            },
        ),
        migrations.CreateModel(
            name='LearningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_id', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=datetime.datetime.utcnow)),
                ('result', models.CharField(max_length=32)),
                ('was_profitable', models.BooleanField()),
                ('market_state', models.CharField(max_length=32)),
                ('notes', models.TextField()),
                ('symbol', models.CharField(blank=True, db_index=True, max_length=16, null=True)),
                ('profit_pct', models.FloatField(blank=True, null=True)),
                ('hold_hours', models.FloatField(blank=True, null=True)),
                ('entry_signals_json', models.TextField(blank=True, null=True)),
                ('entry_rsi', models.FloatField(blank=True, null=True)),
                ('entry_macd_hist', models.FloatField(blank=True, null=True)),
                ('entry_trend', models.CharField(blank=True, max_length=16, null=True)),
                ('entry_up_prob', models.FloatField(blank=True, null=True)),
                ('entry_bb_pos', models.FloatField(blank=True, null=True)),
                ('exit_rsi', models.FloatField(blank=True, null=True)),
                ('exit_macd_hist', models.FloatField(blank=True, null=True)),
                ('exit_trend', models.CharField(blank=True, max_length=16, null=True)),
                ('exit_up_prob', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'learning_log',
            },
        ),
        migrations.CreateModel(
            name='LeverageSimTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=16)),
                ('side', models.CharField(max_length=8)),
                ('leverage', models.FloatField(default=2.0)),
                ('entry_price', models.FloatField()),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('quantity', models.FloatField()),
                ('margin_used', models.FloatField()),
                ('liquidation_price', models.FloatField()),
                ('take_profit', models.FloatField(blank=True, null=True)),
                ('stop_loss', models.FloatField(blank=True, null=True)),
                ('funding_fees', models.FloatField(default=0.0)),
                ('pnl', models.FloatField(blank=True, null=True)),
                ('pnl_pct', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, default='OPEN', max_length=16)),
                ('close_reason', models.CharField(blank=True, max_length=32, null=True)),
                ('decision_score', models.IntegerField(default=0)),
                ('decision_reason', models.TextField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(db_index=True, default=datetime.datetime.utcnow)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'leverage_sim_trades',
            },
        ),
        migrations.CreateModel(
            name='LiveOrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=datetime.datetime.utcnow)),
                ('username', models.CharField(max_length=64)),
                ('symbol', models.CharField(max_length=32)),
                ('action', models.CharField(max_length=8)),
                ('status', models.CharField(max_length=16)),
                ('detail', models.TextField(blank=True, null=True)),
                ('order_id', models.CharField(blank=True, max_length=64, null=True)),
                ('allocation', models.FloatField(blank=True, null=True)),
                ('quote_currency', models.CharField(blank=True, max_length=8, null=True)),
                ('commission', models.FloatField(blank=True, null=True)),
                ('commission_asset', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'live_order_log',
            },
        ),
        migrations.CreateModel(
            name='OpenAIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=datetime.datetime.utcnow)),
                ('model', models.CharField(max_length=64)),
                ('symbol', models.CharField(blank=True, max_length=16, null=True)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('estimated_cost_usd', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'openai_usage_log',
            },
        ),
        migrations.CreateModel(
            name='RuntimeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('value', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'runtime_settings',
            },
        ),
        migrations.CreateModel(
            name='SignalPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('total_fired', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('avg_profit_pct', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'signal_performance',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, max_length=255, unique=True)),
                ('username', models.CharField(db_index=True, max_length=64, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('salt', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('trading_mode', models.CharField(default='PAPER', max_length=16)),
                ('agent_mode', models.CharField(default='normal', max_length=16)),
                ('live_alloc_mode', models.CharField(default='percent', max_length=16)),
                ('live_alloc_value', models.FloatField(default=10.0)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='WhaleAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=datetime.datetime.utcnow)),
                ('symbol', models.CharField(db_index=True, max_length=16)),
                ('signal_type', models.CharField(max_length=32)),
                ('whale_score', models.FloatField()),
                ('vol_zscore', models.FloatField(default=0)),
                ('vol_ratio', models.FloatField(default=1)),
                ('price_change_pct', models.FloatField(default=0)),
                ('obv_divergence', models.CharField(blank=True, max_length=16, null=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'whale_alerts',
            },
        ),
        migrations.CreateModel(
            name='FeatureSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=16)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('rsi', models.FloatField()),
                ('macd', models.FloatField()),
                ('macd_signal', models.FloatField()),
                ('ema20', models.FloatField()),
                ('ema50', models.FloatField()),
                ('trend', models.CharField(max_length=16)),
                ('volume_change', models.FloatField()),
            ],
            options={
                'db_table': 'features',
                'constraints': [models.UniqueConstraint(fields=('symbol', 'timestamp'), name='uq_features_symbol_timestamp')],
            },
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=16)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
                ('source', models.CharField(default='coingecko', max_length=32)),
            ],
            options={
                'db_table': 'market_data',
                'constraints': [models.UniqueConstraint(fields=('symbol', 'timestamp', 'source'), name='uq_market_data_symbol_timestamp_source')],
            },
        ),
        migrations.CreateModel(
            name='SimulatedTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=16)),
                ('buy_price', models.FloatField()),
                ('sell_price', models.FloatField(blank=True, null=True)),
                ('quantity', models.FloatField()),
                ('buy_value', models.FloatField()),
                ('sell_value', models.FloatField(blank=True, null=True)),
                ('buy_fee', models.FloatField()),
                ('sell_fee', models.FloatField(blank=True, null=True)),
                ('profit', models.FloatField(blank=True, null=True)),
                ('duration_minutes', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, default='OPEN', max_length=16)),
                ('opened_at', models.DateTimeField(db_index=True, default=datetime.datetime.utcnow)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='app.decision')),
            ],
            options={
                'db_table': 'simulated_trades',
            },
        ),
        migrations.CreateModel(
            name='UserAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(default='binance', max_length=32)),
                ('label', models.CharField(max_length=64)),
                ('api_key', models.CharField(max_length=128)),
                ('api_secret_encrypted', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('is_testnet', models.BooleanField(default=False)),
                ('permissions', models.CharField(default='read', max_length=64)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='app.user')),
            ],
            options={
                'db_table': 'user_api_keys',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('expires_at', models.DateTimeField()),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='app.user')),
            ],
            options={
                'db_table': 'user_sessions',
            },
        ),
    ]
